version: 0.24.0-{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  matrix:
  - BUILD: x86
    QTDIR: C:\Qt\5.12\msvc2017
  - BUILD: x64
    QTDIR: C:\Qt\5.12\msvc2017_64
install:
- ps: (Get-Content plugins/plugins.pro).replace("spellchecker ", '') | Set-Content plugins/plugins.pro
build_script:
- cmd: >-
    git clone -b windows_files --single-branch https://github.com/inyokaproject/inyokaedit.git windows_files

    git clone -b community --single-branch https://github.com/inyokaproject/inyokaedit.git community

    set PATH=%QTDIR%\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %BUILD%

    qmake inyokaedit.pro

    lrelease application\application.pro

    lrelease plugins\highlighter\highlighter.pro

    lrelease plugins\hotkey\hotkey.pro

    lrelease plugins\uu_knowledgebox\uu_knowledgebox.pro

    lrelease plugins\uu_tabletemplate\uu_tabletemplate.pro

    nmake

    mkdir InyokaEdit\plugins

    mkdir InyokaEdit\community

    copy release\..\InyokaEdit.exe InyokaEdit\InyokaEdit.exe

    windeployqt --release --no-translations --no-angle --no-opengl-sw InyokaEdit\InyokaEdit.exe

    copy COPYING InyokaEdit\

    copy README.md InyokaEdit\

    copy windows_files\OpenSSL_%BUILD%\* InyokaEdit\

    echo n | copy /-y windows_files\bearer\qnativewifibearer.dll InyokaEdit\bearer\

    copy release\..\plugins\*.dll InyokaEdit\plugins\

    chcp 65001 && xcopy /i /e /s community\* InyokaEdit\community\

    rmdir /S /Q InyokaEdit\iconengines

    rmdir /S /Q InyokaEdit\imageformats

    rmdir /S /Q InyokaEdit\position

    7z a InyokaEdit-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip .\InyokaEdit\
artifacts:
- path: InyokaEdit-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip
